### ISSUE TITLE
Crash when configuring the pycharm-debug.egg path

### ISSUE THREAD

**Issue by bpaniagua** [SlicerRt/SlicerDebuggingTools#4]
Following the instructions of the tutorial http://wiki.slicer.org/slicerWiki/index.php/Documentation/Nightly/Extensions/DebuggingTools. The application crashes without showing a folder dialog after clicking the selector.

I have reproduced this error with two different compiled versions of Slicer. 

Update: The application does not crash if the path of pycharm-debug.egg is manually typed. After that everything works correctly.

**Comment by lassoan** [comment]
Qt's folder selector is not very robust and known to crash or hang for a long time. It is usually due to invalid network drive mappings, so you can try to remove them if you have any.
If the file dialog opening still causes crash then copy-paste the path of the egg file in the text box area manually.
